#%RAML 1.0
title: EMP contracts
version: v0.0.1
description: API definition for EMP
documentation:
  - title: EMP
    content: |
      API definition for EMP
protocols: [HTTP]
baseUri: http://{domain_name}/
baseUriParameters:
  domain_name:
    description: Domain name for service or load balancer.

/payslip:
  description: Payslips

  post:
    description: Create payslip.
    body:
      application/json:
        type: |
          {
            "type": "object",
            "properties": {
              "first_name":{
                "type": "string"
              },
              "last_name":{
                "type": "string"
              },
              "annual_salary":{
                "type": "integer"
              },
              "year":{
                "type": "integer"
              },
              "month":{
                "type": "string"
              }
            },
            "required": [
              "first_name",
              "last_name",
              "annual_salary",
              "year",
              "month"
            ]
          }
        example: |
          {
            "first_name": "Sean",
              "last_name": "Van Osselaer",
              "annual_salary": 175000,
              "year": 2017,
              "month": "APRIL"
          }
    responses:
      201:
        description: The payslip was created.
        headers:
          Location:
            description: Uniform Resource Identifier (URI) for the created payslip.
            example: /payslip/{payslip_id}
